// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.32.0
// source: api/proto/etcdisc/v1/etcdisc.proto

package etcdiscv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	wrapperspb "google.golang.org/protobuf/types/known/wrapperspb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ProbeConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Address       string                 `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	Port          int32                  `protobuf:"varint,2,opt,name=port,proto3" json:"port,omitempty"`
	Path          string                 `protobuf:"bytes,3,opt,name=path,proto3" json:"path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProbeConfig) Reset() {
	*x = ProbeConfig{}
	mi := &file_api_proto_etcdisc_v1_etcdisc_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProbeConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProbeConfig) ProtoMessage() {}

func (x *ProbeConfig) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_etcdisc_v1_etcdisc_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProbeConfig.ProtoReflect.Descriptor instead.
func (*ProbeConfig) Descriptor() ([]byte, []int) {
	return file_api_proto_etcdisc_v1_etcdisc_proto_rawDescGZIP(), []int{0}
}

func (x *ProbeConfig) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *ProbeConfig) GetPort() int32 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *ProbeConfig) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

type Namespace struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	AccessMode    string                 `protobuf:"bytes,2,opt,name=access_mode,json=accessMode,proto3" json:"access_mode,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	Revision      int64                  `protobuf:"varint,5,opt,name=revision,proto3" json:"revision,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Namespace) Reset() {
	*x = Namespace{}
	mi := &file_api_proto_etcdisc_v1_etcdisc_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Namespace) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Namespace) ProtoMessage() {}

func (x *Namespace) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_etcdisc_v1_etcdisc_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Namespace.ProtoReflect.Descriptor instead.
func (*Namespace) Descriptor() ([]byte, []int) {
	return file_api_proto_etcdisc_v1_etcdisc_proto_rawDescGZIP(), []int{1}
}

func (x *Namespace) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Namespace) GetAccessMode() string {
	if x != nil {
		return x.AccessMode
	}
	return ""
}

func (x *Namespace) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Namespace) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *Namespace) GetRevision() int64 {
	if x != nil {
		return x.Revision
	}
	return 0
}

type Instance struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	Namespace            string                 `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Service              string                 `protobuf:"bytes,2,opt,name=service,proto3" json:"service,omitempty"`
	Group                string                 `protobuf:"bytes,3,opt,name=group,proto3" json:"group,omitempty"`
	Version              string                 `protobuf:"bytes,4,opt,name=version,proto3" json:"version,omitempty"`
	Weight               int32                  `protobuf:"varint,5,opt,name=weight,proto3" json:"weight,omitempty"`
	InstanceId           string                 `protobuf:"bytes,6,opt,name=instance_id,json=instanceId,proto3" json:"instance_id,omitempty"`
	AgentId              string                 `protobuf:"bytes,7,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	Address              string                 `protobuf:"bytes,8,opt,name=address,proto3" json:"address,omitempty"`
	Port                 int32                  `protobuf:"varint,9,opt,name=port,proto3" json:"port,omitempty"`
	Metadata             map[string]string      `protobuf:"bytes,10,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	HealthCheckMode      string                 `protobuf:"bytes,11,opt,name=health_check_mode,json=healthCheckMode,proto3" json:"health_check_mode,omitempty"`
	ProbeConfig          *ProbeConfig           `protobuf:"bytes,12,opt,name=probe_config,json=probeConfig,proto3" json:"probe_config,omitempty"`
	Status               string                 `protobuf:"bytes,13,opt,name=status,proto3" json:"status,omitempty"`
	LeaseId              int64                  `protobuf:"varint,14,opt,name=lease_id,json=leaseId,proto3" json:"lease_id,omitempty"`
	ConsecutiveFailures  int32                  `protobuf:"varint,15,opt,name=consecutive_failures,json=consecutiveFailures,proto3" json:"consecutive_failures,omitempty"`
	ConsecutiveSuccesses int32                  `protobuf:"varint,16,opt,name=consecutive_successes,json=consecutiveSuccesses,proto3" json:"consecutive_successes,omitempty"`
	LastHeartbeatAt      *timestamppb.Timestamp `protobuf:"bytes,17,opt,name=last_heartbeat_at,json=lastHeartbeatAt,proto3" json:"last_heartbeat_at,omitempty"`
	LastProbeAt          *timestamppb.Timestamp `protobuf:"bytes,18,opt,name=last_probe_at,json=lastProbeAt,proto3" json:"last_probe_at,omitempty"`
	CreatedAt            *timestamppb.Timestamp `protobuf:"bytes,19,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt            *timestamppb.Timestamp `protobuf:"bytes,20,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	StatusUpdatedAt      *timestamppb.Timestamp `protobuf:"bytes,21,opt,name=status_updated_at,json=statusUpdatedAt,proto3" json:"status_updated_at,omitempty"`
	Revision             int64                  `protobuf:"varint,22,opt,name=revision,proto3" json:"revision,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *Instance) Reset() {
	*x = Instance{}
	mi := &file_api_proto_etcdisc_v1_etcdisc_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Instance) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Instance) ProtoMessage() {}

func (x *Instance) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_etcdisc_v1_etcdisc_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Instance.ProtoReflect.Descriptor instead.
func (*Instance) Descriptor() ([]byte, []int) {
	return file_api_proto_etcdisc_v1_etcdisc_proto_rawDescGZIP(), []int{2}
}

func (x *Instance) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *Instance) GetService() string {
	if x != nil {
		return x.Service
	}
	return ""
}

func (x *Instance) GetGroup() string {
	if x != nil {
		return x.Group
	}
	return ""
}

func (x *Instance) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *Instance) GetWeight() int32 {
	if x != nil {
		return x.Weight
	}
	return 0
}

func (x *Instance) GetInstanceId() string {
	if x != nil {
		return x.InstanceId
	}
	return ""
}

func (x *Instance) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *Instance) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *Instance) GetPort() int32 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *Instance) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *Instance) GetHealthCheckMode() string {
	if x != nil {
		return x.HealthCheckMode
	}
	return ""
}

func (x *Instance) GetProbeConfig() *ProbeConfig {
	if x != nil {
		return x.ProbeConfig
	}
	return nil
}

func (x *Instance) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Instance) GetLeaseId() int64 {
	if x != nil {
		return x.LeaseId
	}
	return 0
}

func (x *Instance) GetConsecutiveFailures() int32 {
	if x != nil {
		return x.ConsecutiveFailures
	}
	return 0
}

func (x *Instance) GetConsecutiveSuccesses() int32 {
	if x != nil {
		return x.ConsecutiveSuccesses
	}
	return 0
}

func (x *Instance) GetLastHeartbeatAt() *timestamppb.Timestamp {
	if x != nil {
		return x.LastHeartbeatAt
	}
	return nil
}

func (x *Instance) GetLastProbeAt() *timestamppb.Timestamp {
	if x != nil {
		return x.LastProbeAt
	}
	return nil
}

func (x *Instance) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Instance) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *Instance) GetStatusUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.StatusUpdatedAt
	}
	return nil
}

func (x *Instance) GetRevision() int64 {
	if x != nil {
		return x.Revision
	}
	return 0
}

type ConfigItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Namespace     string                 `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Service       string                 `protobuf:"bytes,2,opt,name=service,proto3" json:"service,omitempty"`
	Scope         string                 `protobuf:"bytes,3,opt,name=scope,proto3" json:"scope,omitempty"`
	Key           string                 `protobuf:"bytes,4,opt,name=key,proto3" json:"key,omitempty"`
	Value         string                 `protobuf:"bytes,5,opt,name=value,proto3" json:"value,omitempty"`
	ValueType     string                 `protobuf:"bytes,6,opt,name=value_type,json=valueType,proto3" json:"value_type,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	Revision      int64                  `protobuf:"varint,9,opt,name=revision,proto3" json:"revision,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfigItem) Reset() {
	*x = ConfigItem{}
	mi := &file_api_proto_etcdisc_v1_etcdisc_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigItem) ProtoMessage() {}

func (x *ConfigItem) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_etcdisc_v1_etcdisc_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigItem.ProtoReflect.Descriptor instead.
func (*ConfigItem) Descriptor() ([]byte, []int) {
	return file_api_proto_etcdisc_v1_etcdisc_proto_rawDescGZIP(), []int{3}
}

func (x *ConfigItem) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *ConfigItem) GetService() string {
	if x != nil {
		return x.Service
	}
	return ""
}

func (x *ConfigItem) GetScope() string {
	if x != nil {
		return x.Scope
	}
	return ""
}

func (x *ConfigItem) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *ConfigItem) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *ConfigItem) GetValueType() string {
	if x != nil {
		return x.ValueType
	}
	return ""
}

func (x *ConfigItem) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *ConfigItem) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *ConfigItem) GetRevision() int64 {
	if x != nil {
		return x.Revision
	}
	return 0
}

type EffectiveConfigItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value         string                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	ValueType     string                 `protobuf:"bytes,3,opt,name=value_type,json=valueType,proto3" json:"value_type,omitempty"`
	Scope         string                 `protobuf:"bytes,4,opt,name=scope,proto3" json:"scope,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EffectiveConfigItem) Reset() {
	*x = EffectiveConfigItem{}
	mi := &file_api_proto_etcdisc_v1_etcdisc_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EffectiveConfigItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EffectiveConfigItem) ProtoMessage() {}

func (x *EffectiveConfigItem) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_etcdisc_v1_etcdisc_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EffectiveConfigItem.ProtoReflect.Descriptor instead.
func (*EffectiveConfigItem) Descriptor() ([]byte, []int) {
	return file_api_proto_etcdisc_v1_etcdisc_proto_rawDescGZIP(), []int{4}
}

func (x *EffectiveConfigItem) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *EffectiveConfigItem) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *EffectiveConfigItem) GetValueType() string {
	if x != nil {
		return x.ValueType
	}
	return ""
}

func (x *EffectiveConfigItem) GetScope() string {
	if x != nil {
		return x.Scope
	}
	return ""
}

type AgentCard struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Namespace     string                 `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	AgentId       string                 `protobuf:"bytes,2,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	Service       string                 `protobuf:"bytes,3,opt,name=service,proto3" json:"service,omitempty"`
	Capabilities  []string               `protobuf:"bytes,4,rep,name=capabilities,proto3" json:"capabilities,omitempty"`
	Protocols     []string               `protobuf:"bytes,5,rep,name=protocols,proto3" json:"protocols,omitempty"`
	AuthMode      string                 `protobuf:"bytes,6,opt,name=auth_mode,json=authMode,proto3" json:"auth_mode,omitempty"`
	Metadata      map[string]string      `protobuf:"bytes,7,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	Revision      int64                  `protobuf:"varint,10,opt,name=revision,proto3" json:"revision,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentCard) Reset() {
	*x = AgentCard{}
	mi := &file_api_proto_etcdisc_v1_etcdisc_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentCard) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentCard) ProtoMessage() {}

func (x *AgentCard) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_etcdisc_v1_etcdisc_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentCard.ProtoReflect.Descriptor instead.
func (*AgentCard) Descriptor() ([]byte, []int) {
	return file_api_proto_etcdisc_v1_etcdisc_proto_rawDescGZIP(), []int{5}
}

func (x *AgentCard) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *AgentCard) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *AgentCard) GetService() string {
	if x != nil {
		return x.Service
	}
	return ""
}

func (x *AgentCard) GetCapabilities() []string {
	if x != nil {
		return x.Capabilities
	}
	return nil
}

func (x *AgentCard) GetProtocols() []string {
	if x != nil {
		return x.Protocols
	}
	return nil
}

func (x *AgentCard) GetAuthMode() string {
	if x != nil {
		return x.AuthMode
	}
	return ""
}

func (x *AgentCard) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *AgentCard) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *AgentCard) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *AgentCard) GetRevision() int64 {
	if x != nil {
		return x.Revision
	}
	return 0
}

type A2ADiscoveryResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Namespace     string                 `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	AgentId       string                 `protobuf:"bytes,2,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	Service       string                 `protobuf:"bytes,3,opt,name=service,proto3" json:"service,omitempty"`
	Address       string                 `protobuf:"bytes,4,opt,name=address,proto3" json:"address,omitempty"`
	Port          int32                  `protobuf:"varint,5,opt,name=port,proto3" json:"port,omitempty"`
	Protocols     []string               `protobuf:"bytes,6,rep,name=protocols,proto3" json:"protocols,omitempty"`
	AuthMode      string                 `protobuf:"bytes,7,opt,name=auth_mode,json=authMode,proto3" json:"auth_mode,omitempty"`
	Metadata      map[string]string      `protobuf:"bytes,8,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Status        string                 `protobuf:"bytes,9,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *A2ADiscoveryResult) Reset() {
	*x = A2ADiscoveryResult{}
	mi := &file_api_proto_etcdisc_v1_etcdisc_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *A2ADiscoveryResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*A2ADiscoveryResult) ProtoMessage() {}

func (x *A2ADiscoveryResult) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_etcdisc_v1_etcdisc_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use A2ADiscoveryResult.ProtoReflect.Descriptor instead.
func (*A2ADiscoveryResult) Descriptor() ([]byte, []int) {
	return file_api_proto_etcdisc_v1_etcdisc_proto_rawDescGZIP(), []int{6}
}

func (x *A2ADiscoveryResult) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *A2ADiscoveryResult) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *A2ADiscoveryResult) GetService() string {
	if x != nil {
		return x.Service
	}
	return ""
}

func (x *A2ADiscoveryResult) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *A2ADiscoveryResult) GetPort() int32 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *A2ADiscoveryResult) GetProtocols() []string {
	if x != nil {
		return x.Protocols
	}
	return nil
}

func (x *A2ADiscoveryResult) GetAuthMode() string {
	if x != nil {
		return x.AuthMode
	}
	return ""
}

func (x *A2ADiscoveryResult) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *A2ADiscoveryResult) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type WatchEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Resource      string                 `protobuf:"bytes,2,opt,name=resource,proto3" json:"resource,omitempty"`
	Key           string                 `protobuf:"bytes,3,opt,name=key,proto3" json:"key,omitempty"`
	Revision      int64                  `protobuf:"varint,4,opt,name=revision,proto3" json:"revision,omitempty"`
	Value         []byte                 `protobuf:"bytes,5,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WatchEvent) Reset() {
	*x = WatchEvent{}
	mi := &file_api_proto_etcdisc_v1_etcdisc_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WatchEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WatchEvent) ProtoMessage() {}

func (x *WatchEvent) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_etcdisc_v1_etcdisc_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WatchEvent.ProtoReflect.Descriptor instead.
func (*WatchEvent) Descriptor() ([]byte, []int) {
	return file_api_proto_etcdisc_v1_etcdisc_proto_rawDescGZIP(), []int{7}
}

func (x *WatchEvent) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *WatchEvent) GetResource() string {
	if x != nil {
		return x.Resource
	}
	return ""
}

func (x *WatchEvent) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *WatchEvent) GetRevision() int64 {
	if x != nil {
		return x.Revision
	}
	return 0
}

func (x *WatchEvent) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

type RegisterInput struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Instance        *Instance              `protobuf:"bytes,1,opt,name=instance,proto3" json:"instance,omitempty"`
	LeaseTtlSeconds int64                  `protobuf:"varint,2,opt,name=lease_ttl_seconds,json=leaseTtlSeconds,proto3" json:"lease_ttl_seconds,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *RegisterInput) Reset() {
	*x = RegisterInput{}
	mi := &file_api_proto_etcdisc_v1_etcdisc_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterInput) ProtoMessage() {}

func (x *RegisterInput) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_etcdisc_v1_etcdisc_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterInput.ProtoReflect.Descriptor instead.
func (*RegisterInput) Descriptor() ([]byte, []int) {
	return file_api_proto_etcdisc_v1_etcdisc_proto_rawDescGZIP(), []int{8}
}

func (x *RegisterInput) GetInstance() *Instance {
	if x != nil {
		return x.Instance
	}
	return nil
}

func (x *RegisterInput) GetLeaseTtlSeconds() int64 {
	if x != nil {
		return x.LeaseTtlSeconds
	}
	return 0
}

type HeartbeatInput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Namespace     string                 `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Service       string                 `protobuf:"bytes,2,opt,name=service,proto3" json:"service,omitempty"`
	InstanceId    string                 `protobuf:"bytes,3,opt,name=instance_id,json=instanceId,proto3" json:"instance_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatInput) Reset() {
	*x = HeartbeatInput{}
	mi := &file_api_proto_etcdisc_v1_etcdisc_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatInput) ProtoMessage() {}

func (x *HeartbeatInput) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_etcdisc_v1_etcdisc_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatInput.ProtoReflect.Descriptor instead.
func (*HeartbeatInput) Descriptor() ([]byte, []int) {
	return file_api_proto_etcdisc_v1_etcdisc_proto_rawDescGZIP(), []int{9}
}

func (x *HeartbeatInput) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *HeartbeatInput) GetService() string {
	if x != nil {
		return x.Service
	}
	return ""
}

func (x *HeartbeatInput) GetInstanceId() string {
	if x != nil {
		return x.InstanceId
	}
	return ""
}

type UpdateInstanceInput struct {
	state            protoimpl.MessageState  `protogen:"open.v1"`
	Namespace        string                  `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Service          string                  `protobuf:"bytes,2,opt,name=service,proto3" json:"service,omitempty"`
	InstanceId       string                  `protobuf:"bytes,3,opt,name=instance_id,json=instanceId,proto3" json:"instance_id,omitempty"`
	Weight           *wrapperspb.Int32Value  `protobuf:"bytes,4,opt,name=weight,proto3" json:"weight,omitempty"`
	Metadata         map[string]string       `protobuf:"bytes,5,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Version          *wrapperspb.StringValue `protobuf:"bytes,6,opt,name=version,proto3" json:"version,omitempty"`
	ExpectedRevision int64                   `protobuf:"varint,7,opt,name=expected_revision,json=expectedRevision,proto3" json:"expected_revision,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *UpdateInstanceInput) Reset() {
	*x = UpdateInstanceInput{}
	mi := &file_api_proto_etcdisc_v1_etcdisc_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateInstanceInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateInstanceInput) ProtoMessage() {}

func (x *UpdateInstanceInput) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_etcdisc_v1_etcdisc_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateInstanceInput.ProtoReflect.Descriptor instead.
func (*UpdateInstanceInput) Descriptor() ([]byte, []int) {
	return file_api_proto_etcdisc_v1_etcdisc_proto_rawDescGZIP(), []int{10}
}

func (x *UpdateInstanceInput) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *UpdateInstanceInput) GetService() string {
	if x != nil {
		return x.Service
	}
	return ""
}

func (x *UpdateInstanceInput) GetInstanceId() string {
	if x != nil {
		return x.InstanceId
	}
	return ""
}

func (x *UpdateInstanceInput) GetWeight() *wrapperspb.Int32Value {
	if x != nil {
		return x.Weight
	}
	return nil
}

func (x *UpdateInstanceInput) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *UpdateInstanceInput) GetVersion() *wrapperspb.StringValue {
	if x != nil {
		return x.Version
	}
	return nil
}

func (x *UpdateInstanceInput) GetExpectedRevision() int64 {
	if x != nil {
		return x.ExpectedRevision
	}
	return 0
}

type DeregisterInput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Namespace     string                 `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Service       string                 `protobuf:"bytes,2,opt,name=service,proto3" json:"service,omitempty"`
	InstanceId    string                 `protobuf:"bytes,3,opt,name=instance_id,json=instanceId,proto3" json:"instance_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeregisterInput) Reset() {
	*x = DeregisterInput{}
	mi := &file_api_proto_etcdisc_v1_etcdisc_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeregisterInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeregisterInput) ProtoMessage() {}

func (x *DeregisterInput) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_etcdisc_v1_etcdisc_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeregisterInput.ProtoReflect.Descriptor instead.
func (*DeregisterInput) Descriptor() ([]byte, []int) {
	return file_api_proto_etcdisc_v1_etcdisc_proto_rawDescGZIP(), []int{11}
}

func (x *DeregisterInput) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *DeregisterInput) GetService() string {
	if x != nil {
		return x.Service
	}
	return ""
}

func (x *DeregisterInput) GetInstanceId() string {
	if x != nil {
		return x.InstanceId
	}
	return ""
}

type DiscoverySnapshotInput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Namespace     string                 `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Service       string                 `protobuf:"bytes,2,opt,name=service,proto3" json:"service,omitempty"`
	Group         string                 `protobuf:"bytes,3,opt,name=group,proto3" json:"group,omitempty"`
	Version       string                 `protobuf:"bytes,4,opt,name=version,proto3" json:"version,omitempty"`
	Metadata      map[string]string      `protobuf:"bytes,5,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	HealthyOnly   *wrapperspb.BoolValue  `protobuf:"bytes,6,opt,name=healthy_only,json=healthyOnly,proto3" json:"healthy_only,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DiscoverySnapshotInput) Reset() {
	*x = DiscoverySnapshotInput{}
	mi := &file_api_proto_etcdisc_v1_etcdisc_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DiscoverySnapshotInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DiscoverySnapshotInput) ProtoMessage() {}

func (x *DiscoverySnapshotInput) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_etcdisc_v1_etcdisc_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DiscoverySnapshotInput.ProtoReflect.Descriptor instead.
func (*DiscoverySnapshotInput) Descriptor() ([]byte, []int) {
	return file_api_proto_etcdisc_v1_etcdisc_proto_rawDescGZIP(), []int{12}
}

func (x *DiscoverySnapshotInput) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *DiscoverySnapshotInput) GetService() string {
	if x != nil {
		return x.Service
	}
	return ""
}

func (x *DiscoverySnapshotInput) GetGroup() string {
	if x != nil {
		return x.Group
	}
	return ""
}

func (x *DiscoverySnapshotInput) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *DiscoverySnapshotInput) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *DiscoverySnapshotInput) GetHealthyOnly() *wrapperspb.BoolValue {
	if x != nil {
		return x.HealthyOnly
	}
	return nil
}

type DiscoveryWatchInput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Namespace     string                 `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Service       string                 `protobuf:"bytes,2,opt,name=service,proto3" json:"service,omitempty"`
	HealthyOnly   *wrapperspb.BoolValue  `protobuf:"bytes,3,opt,name=healthy_only,json=healthyOnly,proto3" json:"healthy_only,omitempty"`
	Revision      int64                  `protobuf:"varint,4,opt,name=revision,proto3" json:"revision,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DiscoveryWatchInput) Reset() {
	*x = DiscoveryWatchInput{}
	mi := &file_api_proto_etcdisc_v1_etcdisc_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DiscoveryWatchInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DiscoveryWatchInput) ProtoMessage() {}

func (x *DiscoveryWatchInput) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_etcdisc_v1_etcdisc_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DiscoveryWatchInput.ProtoReflect.Descriptor instead.
func (*DiscoveryWatchInput) Descriptor() ([]byte, []int) {
	return file_api_proto_etcdisc_v1_etcdisc_proto_rawDescGZIP(), []int{13}
}

func (x *DiscoveryWatchInput) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *DiscoveryWatchInput) GetService() string {
	if x != nil {
		return x.Service
	}
	return ""
}

func (x *DiscoveryWatchInput) GetHealthyOnly() *wrapperspb.BoolValue {
	if x != nil {
		return x.HealthyOnly
	}
	return nil
}

func (x *DiscoveryWatchInput) GetRevision() int64 {
	if x != nil {
		return x.Revision
	}
	return 0
}

type ConfigPutInput struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Item             *ConfigItem            `protobuf:"bytes,1,opt,name=item,proto3" json:"item,omitempty"`
	ExpectedRevision int64                  `protobuf:"varint,2,opt,name=expected_revision,json=expectedRevision,proto3" json:"expected_revision,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ConfigPutInput) Reset() {
	*x = ConfigPutInput{}
	mi := &file_api_proto_etcdisc_v1_etcdisc_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigPutInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigPutInput) ProtoMessage() {}

func (x *ConfigPutInput) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_etcdisc_v1_etcdisc_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigPutInput.ProtoReflect.Descriptor instead.
func (*ConfigPutInput) Descriptor() ([]byte, []int) {
	return file_api_proto_etcdisc_v1_etcdisc_proto_rawDescGZIP(), []int{14}
}

func (x *ConfigPutInput) GetItem() *ConfigItem {
	if x != nil {
		return x.Item
	}
	return nil
}

func (x *ConfigPutInput) GetExpectedRevision() int64 {
	if x != nil {
		return x.ExpectedRevision
	}
	return 0
}

type ConfigDeleteInput struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Scope            string                 `protobuf:"bytes,1,opt,name=scope,proto3" json:"scope,omitempty"`
	Namespace        string                 `protobuf:"bytes,2,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Service          string                 `protobuf:"bytes,3,opt,name=service,proto3" json:"service,omitempty"`
	Key              string                 `protobuf:"bytes,4,opt,name=key,proto3" json:"key,omitempty"`
	ExpectedRevision int64                  `protobuf:"varint,5,opt,name=expected_revision,json=expectedRevision,proto3" json:"expected_revision,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ConfigDeleteInput) Reset() {
	*x = ConfigDeleteInput{}
	mi := &file_api_proto_etcdisc_v1_etcdisc_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigDeleteInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigDeleteInput) ProtoMessage() {}

func (x *ConfigDeleteInput) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_etcdisc_v1_etcdisc_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigDeleteInput.ProtoReflect.Descriptor instead.
func (*ConfigDeleteInput) Descriptor() ([]byte, []int) {
	return file_api_proto_etcdisc_v1_etcdisc_proto_rawDescGZIP(), []int{15}
}

func (x *ConfigDeleteInput) GetScope() string {
	if x != nil {
		return x.Scope
	}
	return ""
}

func (x *ConfigDeleteInput) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *ConfigDeleteInput) GetService() string {
	if x != nil {
		return x.Service
	}
	return ""
}

func (x *ConfigDeleteInput) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *ConfigDeleteInput) GetExpectedRevision() int64 {
	if x != nil {
		return x.ExpectedRevision
	}
	return 0
}

type ConfigWatchInput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Namespace     string                 `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Service       string                 `protobuf:"bytes,2,opt,name=service,proto3" json:"service,omitempty"`
	Revision      int64                  `protobuf:"varint,3,opt,name=revision,proto3" json:"revision,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfigWatchInput) Reset() {
	*x = ConfigWatchInput{}
	mi := &file_api_proto_etcdisc_v1_etcdisc_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigWatchInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigWatchInput) ProtoMessage() {}

func (x *ConfigWatchInput) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_etcdisc_v1_etcdisc_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigWatchInput.ProtoReflect.Descriptor instead.
func (*ConfigWatchInput) Descriptor() ([]byte, []int) {
	return file_api_proto_etcdisc_v1_etcdisc_proto_rawDescGZIP(), []int{16}
}

func (x *ConfigWatchInput) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *ConfigWatchInput) GetService() string {
	if x != nil {
		return x.Service
	}
	return ""
}

func (x *ConfigWatchInput) GetRevision() int64 {
	if x != nil {
		return x.Revision
	}
	return 0
}

type AgentCardPutInput struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Card             *AgentCard             `protobuf:"bytes,1,opt,name=card,proto3" json:"card,omitempty"`
	ExpectedRevision int64                  `protobuf:"varint,2,opt,name=expected_revision,json=expectedRevision,proto3" json:"expected_revision,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *AgentCardPutInput) Reset() {
	*x = AgentCardPutInput{}
	mi := &file_api_proto_etcdisc_v1_etcdisc_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentCardPutInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentCardPutInput) ProtoMessage() {}

func (x *AgentCardPutInput) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_etcdisc_v1_etcdisc_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentCardPutInput.ProtoReflect.Descriptor instead.
func (*AgentCardPutInput) Descriptor() ([]byte, []int) {
	return file_api_proto_etcdisc_v1_etcdisc_proto_rawDescGZIP(), []int{17}
}

func (x *AgentCardPutInput) GetCard() *AgentCard {
	if x != nil {
		return x.Card
	}
	return nil
}

func (x *AgentCardPutInput) GetExpectedRevision() int64 {
	if x != nil {
		return x.ExpectedRevision
	}
	return 0
}

type CapabilityDiscoverInput struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Namespace        string                 `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Capability       string                 `protobuf:"bytes,2,opt,name=capability,proto3" json:"capability,omitempty"`
	Protocol         string                 `protobuf:"bytes,3,opt,name=protocol,proto3" json:"protocol,omitempty"`
	IncludeUnhealthy *wrapperspb.BoolValue  `protobuf:"bytes,4,opt,name=include_unhealthy,json=includeUnhealthy,proto3" json:"include_unhealthy,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *CapabilityDiscoverInput) Reset() {
	*x = CapabilityDiscoverInput{}
	mi := &file_api_proto_etcdisc_v1_etcdisc_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CapabilityDiscoverInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CapabilityDiscoverInput) ProtoMessage() {}

func (x *CapabilityDiscoverInput) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_etcdisc_v1_etcdisc_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CapabilityDiscoverInput.ProtoReflect.Descriptor instead.
func (*CapabilityDiscoverInput) Descriptor() ([]byte, []int) {
	return file_api_proto_etcdisc_v1_etcdisc_proto_rawDescGZIP(), []int{18}
}

func (x *CapabilityDiscoverInput) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *CapabilityDiscoverInput) GetCapability() string {
	if x != nil {
		return x.Capability
	}
	return ""
}

func (x *CapabilityDiscoverInput) GetProtocol() string {
	if x != nil {
		return x.Protocol
	}
	return ""
}

func (x *CapabilityDiscoverInput) GetIncludeUnhealthy() *wrapperspb.BoolValue {
	if x != nil {
		return x.IncludeUnhealthy
	}
	return nil
}

type RegisterRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Input         *RegisterInput         `protobuf:"bytes,1,opt,name=input,proto3" json:"input,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterRequest) Reset() {
	*x = RegisterRequest{}
	mi := &file_api_proto_etcdisc_v1_etcdisc_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterRequest) ProtoMessage() {}

func (x *RegisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_etcdisc_v1_etcdisc_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterRequest.ProtoReflect.Descriptor instead.
func (*RegisterRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_etcdisc_v1_etcdisc_proto_rawDescGZIP(), []int{19}
}

func (x *RegisterRequest) GetInput() *RegisterInput {
	if x != nil {
		return x.Input
	}
	return nil
}

type RegisterResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Instance      *Instance              `protobuf:"bytes,1,opt,name=instance,proto3" json:"instance,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterResponse) Reset() {
	*x = RegisterResponse{}
	mi := &file_api_proto_etcdisc_v1_etcdisc_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterResponse) ProtoMessage() {}

func (x *RegisterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_etcdisc_v1_etcdisc_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterResponse.ProtoReflect.Descriptor instead.
func (*RegisterResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_etcdisc_v1_etcdisc_proto_rawDescGZIP(), []int{20}
}

func (x *RegisterResponse) GetInstance() *Instance {
	if x != nil {
		return x.Instance
	}
	return nil
}

type HeartbeatRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Input         *HeartbeatInput        `protobuf:"bytes,1,opt,name=input,proto3" json:"input,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatRequest) Reset() {
	*x = HeartbeatRequest{}
	mi := &file_api_proto_etcdisc_v1_etcdisc_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatRequest) ProtoMessage() {}

func (x *HeartbeatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_etcdisc_v1_etcdisc_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatRequest.ProtoReflect.Descriptor instead.
func (*HeartbeatRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_etcdisc_v1_etcdisc_proto_rawDescGZIP(), []int{21}
}

func (x *HeartbeatRequest) GetInput() *HeartbeatInput {
	if x != nil {
		return x.Input
	}
	return nil
}

type HeartbeatResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Instance      *Instance              `protobuf:"bytes,1,opt,name=instance,proto3" json:"instance,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatResponse) Reset() {
	*x = HeartbeatResponse{}
	mi := &file_api_proto_etcdisc_v1_etcdisc_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatResponse) ProtoMessage() {}

func (x *HeartbeatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_etcdisc_v1_etcdisc_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatResponse.ProtoReflect.Descriptor instead.
func (*HeartbeatResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_etcdisc_v1_etcdisc_proto_rawDescGZIP(), []int{22}
}

func (x *HeartbeatResponse) GetInstance() *Instance {
	if x != nil {
		return x.Instance
	}
	return nil
}

type UpdateInstanceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Input         *UpdateInstanceInput   `protobuf:"bytes,1,opt,name=input,proto3" json:"input,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateInstanceRequest) Reset() {
	*x = UpdateInstanceRequest{}
	mi := &file_api_proto_etcdisc_v1_etcdisc_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateInstanceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateInstanceRequest) ProtoMessage() {}

func (x *UpdateInstanceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_etcdisc_v1_etcdisc_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateInstanceRequest.ProtoReflect.Descriptor instead.
func (*UpdateInstanceRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_etcdisc_v1_etcdisc_proto_rawDescGZIP(), []int{23}
}

func (x *UpdateInstanceRequest) GetInput() *UpdateInstanceInput {
	if x != nil {
		return x.Input
	}
	return nil
}

type UpdateInstanceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Instance      *Instance              `protobuf:"bytes,1,opt,name=instance,proto3" json:"instance,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateInstanceResponse) Reset() {
	*x = UpdateInstanceResponse{}
	mi := &file_api_proto_etcdisc_v1_etcdisc_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateInstanceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateInstanceResponse) ProtoMessage() {}

func (x *UpdateInstanceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_etcdisc_v1_etcdisc_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateInstanceResponse.ProtoReflect.Descriptor instead.
func (*UpdateInstanceResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_etcdisc_v1_etcdisc_proto_rawDescGZIP(), []int{24}
}

func (x *UpdateInstanceResponse) GetInstance() *Instance {
	if x != nil {
		return x.Instance
	}
	return nil
}

type DeregisterRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Input         *DeregisterInput       `protobuf:"bytes,1,opt,name=input,proto3" json:"input,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeregisterRequest) Reset() {
	*x = DeregisterRequest{}
	mi := &file_api_proto_etcdisc_v1_etcdisc_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeregisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeregisterRequest) ProtoMessage() {}

func (x *DeregisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_etcdisc_v1_etcdisc_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeregisterRequest.ProtoReflect.Descriptor instead.
func (*DeregisterRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_etcdisc_v1_etcdisc_proto_rawDescGZIP(), []int{25}
}

func (x *DeregisterRequest) GetInput() *DeregisterInput {
	if x != nil {
		return x.Input
	}
	return nil
}

type DeregisterResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeregisterResponse) Reset() {
	*x = DeregisterResponse{}
	mi := &file_api_proto_etcdisc_v1_etcdisc_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeregisterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeregisterResponse) ProtoMessage() {}

func (x *DeregisterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_etcdisc_v1_etcdisc_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeregisterResponse.ProtoReflect.Descriptor instead.
func (*DeregisterResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_etcdisc_v1_etcdisc_proto_rawDescGZIP(), []int{26}
}

func (x *DeregisterResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type DiscoverRequest struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Input         *DiscoverySnapshotInput `protobuf:"bytes,1,opt,name=input,proto3" json:"input,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DiscoverRequest) Reset() {
	*x = DiscoverRequest{}
	mi := &file_api_proto_etcdisc_v1_etcdisc_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DiscoverRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DiscoverRequest) ProtoMessage() {}

func (x *DiscoverRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_etcdisc_v1_etcdisc_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DiscoverRequest.ProtoReflect.Descriptor instead.
func (*DiscoverRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_etcdisc_v1_etcdisc_proto_rawDescGZIP(), []int{27}
}

func (x *DiscoverRequest) GetInput() *DiscoverySnapshotInput {
	if x != nil {
		return x.Input
	}
	return nil
}

type DiscoverResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*Instance            `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DiscoverResponse) Reset() {
	*x = DiscoverResponse{}
	mi := &file_api_proto_etcdisc_v1_etcdisc_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DiscoverResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DiscoverResponse) ProtoMessage() {}

func (x *DiscoverResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_etcdisc_v1_etcdisc_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DiscoverResponse.ProtoReflect.Descriptor instead.
func (*DiscoverResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_etcdisc_v1_etcdisc_proto_rawDescGZIP(), []int{28}
}

func (x *DiscoverResponse) GetItems() []*Instance {
	if x != nil {
		return x.Items
	}
	return nil
}

type WatchInstancesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Input         *DiscoveryWatchInput   `protobuf:"bytes,1,opt,name=input,proto3" json:"input,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WatchInstancesRequest) Reset() {
	*x = WatchInstancesRequest{}
	mi := &file_api_proto_etcdisc_v1_etcdisc_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WatchInstancesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WatchInstancesRequest) ProtoMessage() {}

func (x *WatchInstancesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_etcdisc_v1_etcdisc_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WatchInstancesRequest.ProtoReflect.Descriptor instead.
func (*WatchInstancesRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_etcdisc_v1_etcdisc_proto_rawDescGZIP(), []int{29}
}

func (x *WatchInstancesRequest) GetInput() *DiscoveryWatchInput {
	if x != nil {
		return x.Input
	}
	return nil
}

type ConfigGetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Namespace     string                 `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Service       string                 `protobuf:"bytes,2,opt,name=service,proto3" json:"service,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfigGetRequest) Reset() {
	*x = ConfigGetRequest{}
	mi := &file_api_proto_etcdisc_v1_etcdisc_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigGetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigGetRequest) ProtoMessage() {}

func (x *ConfigGetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_etcdisc_v1_etcdisc_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigGetRequest.ProtoReflect.Descriptor instead.
func (*ConfigGetRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_etcdisc_v1_etcdisc_proto_rawDescGZIP(), []int{30}
}

func (x *ConfigGetRequest) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *ConfigGetRequest) GetService() string {
	if x != nil {
		return x.Service
	}
	return ""
}

type ConfigGetResponse struct {
	state           protoimpl.MessageState          `protogen:"open.v1"`
	EffectiveConfig map[string]*EffectiveConfigItem `protobuf:"bytes,1,rep,name=effective_config,json=effectiveConfig,proto3" json:"effective_config,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ConfigGetResponse) Reset() {
	*x = ConfigGetResponse{}
	mi := &file_api_proto_etcdisc_v1_etcdisc_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigGetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigGetResponse) ProtoMessage() {}

func (x *ConfigGetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_etcdisc_v1_etcdisc_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigGetResponse.ProtoReflect.Descriptor instead.
func (*ConfigGetResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_etcdisc_v1_etcdisc_proto_rawDescGZIP(), []int{31}
}

func (x *ConfigGetResponse) GetEffectiveConfig() map[string]*EffectiveConfigItem {
	if x != nil {
		return x.EffectiveConfig
	}
	return nil
}

type ConfigPutRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Input         *ConfigPutInput        `protobuf:"bytes,1,opt,name=input,proto3" json:"input,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfigPutRequest) Reset() {
	*x = ConfigPutRequest{}
	mi := &file_api_proto_etcdisc_v1_etcdisc_proto_msgTypes[32]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigPutRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigPutRequest) ProtoMessage() {}

func (x *ConfigPutRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_etcdisc_v1_etcdisc_proto_msgTypes[32]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigPutRequest.ProtoReflect.Descriptor instead.
func (*ConfigPutRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_etcdisc_v1_etcdisc_proto_rawDescGZIP(), []int{32}
}

func (x *ConfigPutRequest) GetInput() *ConfigPutInput {
	if x != nil {
		return x.Input
	}
	return nil
}

type ConfigPutResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Item          *ConfigItem            `protobuf:"bytes,1,opt,name=item,proto3" json:"item,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfigPutResponse) Reset() {
	*x = ConfigPutResponse{}
	mi := &file_api_proto_etcdisc_v1_etcdisc_proto_msgTypes[33]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigPutResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigPutResponse) ProtoMessage() {}

func (x *ConfigPutResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_etcdisc_v1_etcdisc_proto_msgTypes[33]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigPutResponse.ProtoReflect.Descriptor instead.
func (*ConfigPutResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_etcdisc_v1_etcdisc_proto_rawDescGZIP(), []int{33}
}

func (x *ConfigPutResponse) GetItem() *ConfigItem {
	if x != nil {
		return x.Item
	}
	return nil
}

type ConfigDeleteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Input         *ConfigDeleteInput     `protobuf:"bytes,1,opt,name=input,proto3" json:"input,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfigDeleteRequest) Reset() {
	*x = ConfigDeleteRequest{}
	mi := &file_api_proto_etcdisc_v1_etcdisc_proto_msgTypes[34]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigDeleteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigDeleteRequest) ProtoMessage() {}

func (x *ConfigDeleteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_etcdisc_v1_etcdisc_proto_msgTypes[34]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigDeleteRequest.ProtoReflect.Descriptor instead.
func (*ConfigDeleteRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_etcdisc_v1_etcdisc_proto_rawDescGZIP(), []int{34}
}

func (x *ConfigDeleteRequest) GetInput() *ConfigDeleteInput {
	if x != nil {
		return x.Input
	}
	return nil
}

type ConfigDeleteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfigDeleteResponse) Reset() {
	*x = ConfigDeleteResponse{}
	mi := &file_api_proto_etcdisc_v1_etcdisc_proto_msgTypes[35]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigDeleteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigDeleteResponse) ProtoMessage() {}

func (x *ConfigDeleteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_etcdisc_v1_etcdisc_proto_msgTypes[35]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigDeleteResponse.ProtoReflect.Descriptor instead.
func (*ConfigDeleteResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_etcdisc_v1_etcdisc_proto_rawDescGZIP(), []int{35}
}

func (x *ConfigDeleteResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type WatchConfigsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Input         *ConfigWatchInput      `protobuf:"bytes,1,opt,name=input,proto3" json:"input,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WatchConfigsRequest) Reset() {
	*x = WatchConfigsRequest{}
	mi := &file_api_proto_etcdisc_v1_etcdisc_proto_msgTypes[36]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WatchConfigsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WatchConfigsRequest) ProtoMessage() {}

func (x *WatchConfigsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_etcdisc_v1_etcdisc_proto_msgTypes[36]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WatchConfigsRequest.ProtoReflect.Descriptor instead.
func (*WatchConfigsRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_etcdisc_v1_etcdisc_proto_rawDescGZIP(), []int{36}
}

func (x *WatchConfigsRequest) GetInput() *ConfigWatchInput {
	if x != nil {
		return x.Input
	}
	return nil
}

type UpsertAgentCardRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Input         *AgentCardPutInput     `protobuf:"bytes,1,opt,name=input,proto3" json:"input,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpsertAgentCardRequest) Reset() {
	*x = UpsertAgentCardRequest{}
	mi := &file_api_proto_etcdisc_v1_etcdisc_proto_msgTypes[37]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpsertAgentCardRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpsertAgentCardRequest) ProtoMessage() {}

func (x *UpsertAgentCardRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_etcdisc_v1_etcdisc_proto_msgTypes[37]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpsertAgentCardRequest.ProtoReflect.Descriptor instead.
func (*UpsertAgentCardRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_etcdisc_v1_etcdisc_proto_rawDescGZIP(), []int{37}
}

func (x *UpsertAgentCardRequest) GetInput() *AgentCardPutInput {
	if x != nil {
		return x.Input
	}
	return nil
}

type UpsertAgentCardResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Card          *AgentCard             `protobuf:"bytes,1,opt,name=card,proto3" json:"card,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpsertAgentCardResponse) Reset() {
	*x = UpsertAgentCardResponse{}
	mi := &file_api_proto_etcdisc_v1_etcdisc_proto_msgTypes[38]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpsertAgentCardResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpsertAgentCardResponse) ProtoMessage() {}

func (x *UpsertAgentCardResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_etcdisc_v1_etcdisc_proto_msgTypes[38]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpsertAgentCardResponse.ProtoReflect.Descriptor instead.
func (*UpsertAgentCardResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_etcdisc_v1_etcdisc_proto_rawDescGZIP(), []int{38}
}

func (x *UpsertAgentCardResponse) GetCard() *AgentCard {
	if x != nil {
		return x.Card
	}
	return nil
}

type DiscoverCapabilitiesRequest struct {
	state         protoimpl.MessageState   `protogen:"open.v1"`
	Input         *CapabilityDiscoverInput `protobuf:"bytes,1,opt,name=input,proto3" json:"input,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DiscoverCapabilitiesRequest) Reset() {
	*x = DiscoverCapabilitiesRequest{}
	mi := &file_api_proto_etcdisc_v1_etcdisc_proto_msgTypes[39]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DiscoverCapabilitiesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DiscoverCapabilitiesRequest) ProtoMessage() {}

func (x *DiscoverCapabilitiesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_etcdisc_v1_etcdisc_proto_msgTypes[39]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DiscoverCapabilitiesRequest.ProtoReflect.Descriptor instead.
func (*DiscoverCapabilitiesRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_etcdisc_v1_etcdisc_proto_rawDescGZIP(), []int{39}
}

func (x *DiscoverCapabilitiesRequest) GetInput() *CapabilityDiscoverInput {
	if x != nil {
		return x.Input
	}
	return nil
}

type DiscoverCapabilitiesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*A2ADiscoveryResult  `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DiscoverCapabilitiesResponse) Reset() {
	*x = DiscoverCapabilitiesResponse{}
	mi := &file_api_proto_etcdisc_v1_etcdisc_proto_msgTypes[40]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DiscoverCapabilitiesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DiscoverCapabilitiesResponse) ProtoMessage() {}

func (x *DiscoverCapabilitiesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_etcdisc_v1_etcdisc_proto_msgTypes[40]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DiscoverCapabilitiesResponse.ProtoReflect.Descriptor instead.
func (*DiscoverCapabilitiesResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_etcdisc_v1_etcdisc_proto_rawDescGZIP(), []int{40}
}

func (x *DiscoverCapabilitiesResponse) GetItems() []*A2ADiscoveryResult {
	if x != nil {
		return x.Items
	}
	return nil
}

var File_api_proto_etcdisc_v1_etcdisc_proto protoreflect.FileDescriptor

const file_api_proto_etcdisc_v1_etcdisc_proto_rawDesc = "" +
	"\n" +
	"\"api/proto/etcdisc/v1/etcdisc.proto\x12\n" +
	"etcdisc.v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1egoogle/protobuf/wrappers.proto\"O\n" +
	"\vProbeConfig\x12\x18\n" +
	"\aaddress\x18\x01 \x01(\tR\aaddress\x12\x12\n" +
	"\x04port\x18\x02 \x01(\x05R\x04port\x12\x12\n" +
	"\x04path\x18\x03 \x01(\tR\x04path\"\xd2\x01\n" +
	"\tNamespace\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1f\n" +
	"\vaccess_mode\x18\x02 \x01(\tR\n" +
	"accessMode\x129\n" +
	"\n" +
	"created_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x12\x1a\n" +
	"\brevision\x18\x05 \x01(\x03R\brevision\"\xd6\a\n" +
	"\bInstance\x12\x1c\n" +
	"\tnamespace\x18\x01 \x01(\tR\tnamespace\x12\x18\n" +
	"\aservice\x18\x02 \x01(\tR\aservice\x12\x14\n" +
	"\x05group\x18\x03 \x01(\tR\x05group\x12\x18\n" +
	"\aversion\x18\x04 \x01(\tR\aversion\x12\x16\n" +
	"\x06weight\x18\x05 \x01(\x05R\x06weight\x12\x1f\n" +
	"\vinstance_id\x18\x06 \x01(\tR\n" +
	"instanceId\x12\x19\n" +
	"\bagent_id\x18\a \x01(\tR\aagentId\x12\x18\n" +
	"\aaddress\x18\b \x01(\tR\aaddress\x12\x12\n" +
	"\x04port\x18\t \x01(\x05R\x04port\x12>\n" +
	"\bmetadata\x18\n" +
	" \x03(\v2\".etcdisc.v1.Instance.MetadataEntryR\bmetadata\x12*\n" +
	"\x11health_check_mode\x18\v \x01(\tR\x0fhealthCheckMode\x12:\n" +
	"\fprobe_config\x18\f \x01(\v2\x17.etcdisc.v1.ProbeConfigR\vprobeConfig\x12\x16\n" +
	"\x06status\x18\r \x01(\tR\x06status\x12\x19\n" +
	"\blease_id\x18\x0e \x01(\x03R\aleaseId\x121\n" +
	"\x14consecutive_failures\x18\x0f \x01(\x05R\x13consecutiveFailures\x123\n" +
	"\x15consecutive_successes\x18\x10 \x01(\x05R\x14consecutiveSuccesses\x12F\n" +
	"\x11last_heartbeat_at\x18\x11 \x01(\v2\x1a.google.protobuf.TimestampR\x0flastHeartbeatAt\x12>\n" +
	"\rlast_probe_at\x18\x12 \x01(\v2\x1a.google.protobuf.TimestampR\vlastProbeAt\x129\n" +
	"\n" +
	"created_at\x18\x13 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x14 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x12F\n" +
	"\x11status_updated_at\x18\x15 \x01(\v2\x1a.google.protobuf.TimestampR\x0fstatusUpdatedAt\x12\x1a\n" +
	"\brevision\x18\x16 \x01(\x03R\brevision\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xb3\x02\n" +
	"\n" +
	"ConfigItem\x12\x1c\n" +
	"\tnamespace\x18\x01 \x01(\tR\tnamespace\x12\x18\n" +
	"\aservice\x18\x02 \x01(\tR\aservice\x12\x14\n" +
	"\x05scope\x18\x03 \x01(\tR\x05scope\x12\x10\n" +
	"\x03key\x18\x04 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x05 \x01(\tR\x05value\x12\x1d\n" +
	"\n" +
	"value_type\x18\x06 \x01(\tR\tvalueType\x129\n" +
	"\n" +
	"created_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x12\x1a\n" +
	"\brevision\x18\t \x01(\x03R\brevision\"r\n" +
	"\x13EffectiveConfigItem\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value\x12\x1d\n" +
	"\n" +
	"value_type\x18\x03 \x01(\tR\tvalueType\x12\x14\n" +
	"\x05scope\x18\x04 \x01(\tR\x05scope\"\xcd\x03\n" +
	"\tAgentCard\x12\x1c\n" +
	"\tnamespace\x18\x01 \x01(\tR\tnamespace\x12\x19\n" +
	"\bagent_id\x18\x02 \x01(\tR\aagentId\x12\x18\n" +
	"\aservice\x18\x03 \x01(\tR\aservice\x12\"\n" +
	"\fcapabilities\x18\x04 \x03(\tR\fcapabilities\x12\x1c\n" +
	"\tprotocols\x18\x05 \x03(\tR\tprotocols\x12\x1b\n" +
	"\tauth_mode\x18\x06 \x01(\tR\bauthMode\x12?\n" +
	"\bmetadata\x18\a \x03(\v2#.etcdisc.v1.AgentCard.MetadataEntryR\bmetadata\x129\n" +
	"\n" +
	"created_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x12\x1a\n" +
	"\brevision\x18\n" +
	" \x01(\x03R\brevision\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xef\x02\n" +
	"\x12A2ADiscoveryResult\x12\x1c\n" +
	"\tnamespace\x18\x01 \x01(\tR\tnamespace\x12\x19\n" +
	"\bagent_id\x18\x02 \x01(\tR\aagentId\x12\x18\n" +
	"\aservice\x18\x03 \x01(\tR\aservice\x12\x18\n" +
	"\aaddress\x18\x04 \x01(\tR\aaddress\x12\x12\n" +
	"\x04port\x18\x05 \x01(\x05R\x04port\x12\x1c\n" +
	"\tprotocols\x18\x06 \x03(\tR\tprotocols\x12\x1b\n" +
	"\tauth_mode\x18\a \x01(\tR\bauthMode\x12H\n" +
	"\bmetadata\x18\b \x03(\v2,.etcdisc.v1.A2ADiscoveryResult.MetadataEntryR\bmetadata\x12\x16\n" +
	"\x06status\x18\t \x01(\tR\x06status\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x80\x01\n" +
	"\n" +
	"WatchEvent\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x1a\n" +
	"\bresource\x18\x02 \x01(\tR\bresource\x12\x10\n" +
	"\x03key\x18\x03 \x01(\tR\x03key\x12\x1a\n" +
	"\brevision\x18\x04 \x01(\x03R\brevision\x12\x14\n" +
	"\x05value\x18\x05 \x01(\fR\x05value\"m\n" +
	"\rRegisterInput\x120\n" +
	"\binstance\x18\x01 \x01(\v2\x14.etcdisc.v1.InstanceR\binstance\x12*\n" +
	"\x11lease_ttl_seconds\x18\x02 \x01(\x03R\x0fleaseTtlSeconds\"i\n" +
	"\x0eHeartbeatInput\x12\x1c\n" +
	"\tnamespace\x18\x01 \x01(\tR\tnamespace\x12\x18\n" +
	"\aservice\x18\x02 \x01(\tR\aservice\x12\x1f\n" +
	"\vinstance_id\x18\x03 \x01(\tR\n" +
	"instanceId\"\x90\x03\n" +
	"\x13UpdateInstanceInput\x12\x1c\n" +
	"\tnamespace\x18\x01 \x01(\tR\tnamespace\x12\x18\n" +
	"\aservice\x18\x02 \x01(\tR\aservice\x12\x1f\n" +
	"\vinstance_id\x18\x03 \x01(\tR\n" +
	"instanceId\x123\n" +
	"\x06weight\x18\x04 \x01(\v2\x1b.google.protobuf.Int32ValueR\x06weight\x12I\n" +
	"\bmetadata\x18\x05 \x03(\v2-.etcdisc.v1.UpdateInstanceInput.MetadataEntryR\bmetadata\x126\n" +
	"\aversion\x18\x06 \x01(\v2\x1c.google.protobuf.StringValueR\aversion\x12+\n" +
	"\x11expected_revision\x18\a \x01(\x03R\x10expectedRevision\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"j\n" +
	"\x0fDeregisterInput\x12\x1c\n" +
	"\tnamespace\x18\x01 \x01(\tR\tnamespace\x12\x18\n" +
	"\aservice\x18\x02 \x01(\tR\aservice\x12\x1f\n" +
	"\vinstance_id\x18\x03 \x01(\tR\n" +
	"instanceId\"\xca\x02\n" +
	"\x16DiscoverySnapshotInput\x12\x1c\n" +
	"\tnamespace\x18\x01 \x01(\tR\tnamespace\x12\x18\n" +
	"\aservice\x18\x02 \x01(\tR\aservice\x12\x14\n" +
	"\x05group\x18\x03 \x01(\tR\x05group\x12\x18\n" +
	"\aversion\x18\x04 \x01(\tR\aversion\x12L\n" +
	"\bmetadata\x18\x05 \x03(\v20.etcdisc.v1.DiscoverySnapshotInput.MetadataEntryR\bmetadata\x12=\n" +
	"\fhealthy_only\x18\x06 \x01(\v2\x1a.google.protobuf.BoolValueR\vhealthyOnly\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xa8\x01\n" +
	"\x13DiscoveryWatchInput\x12\x1c\n" +
	"\tnamespace\x18\x01 \x01(\tR\tnamespace\x12\x18\n" +
	"\aservice\x18\x02 \x01(\tR\aservice\x12=\n" +
	"\fhealthy_only\x18\x03 \x01(\v2\x1a.google.protobuf.BoolValueR\vhealthyOnly\x12\x1a\n" +
	"\brevision\x18\x04 \x01(\x03R\brevision\"i\n" +
	"\x0eConfigPutInput\x12*\n" +
	"\x04item\x18\x01 \x01(\v2\x16.etcdisc.v1.ConfigItemR\x04item\x12+\n" +
	"\x11expected_revision\x18\x02 \x01(\x03R\x10expectedRevision\"\xa0\x01\n" +
	"\x11ConfigDeleteInput\x12\x14\n" +
	"\x05scope\x18\x01 \x01(\tR\x05scope\x12\x1c\n" +
	"\tnamespace\x18\x02 \x01(\tR\tnamespace\x12\x18\n" +
	"\aservice\x18\x03 \x01(\tR\aservice\x12\x10\n" +
	"\x03key\x18\x04 \x01(\tR\x03key\x12+\n" +
	"\x11expected_revision\x18\x05 \x01(\x03R\x10expectedRevision\"f\n" +
	"\x10ConfigWatchInput\x12\x1c\n" +
	"\tnamespace\x18\x01 \x01(\tR\tnamespace\x12\x18\n" +
	"\aservice\x18\x02 \x01(\tR\aservice\x12\x1a\n" +
	"\brevision\x18\x03 \x01(\x03R\brevision\"k\n" +
	"\x11AgentCardPutInput\x12)\n" +
	"\x04card\x18\x01 \x01(\v2\x15.etcdisc.v1.AgentCardR\x04card\x12+\n" +
	"\x11expected_revision\x18\x02 \x01(\x03R\x10expectedRevision\"\xbc\x01\n" +
	"\x17CapabilityDiscoverInput\x12\x1c\n" +
	"\tnamespace\x18\x01 \x01(\tR\tnamespace\x12\x1e\n" +
	"\n" +
	"capability\x18\x02 \x01(\tR\n" +
	"capability\x12\x1a\n" +
	"\bprotocol\x18\x03 \x01(\tR\bprotocol\x12G\n" +
	"\x11include_unhealthy\x18\x04 \x01(\v2\x1a.google.protobuf.BoolValueR\x10includeUnhealthy\"B\n" +
	"\x0fRegisterRequest\x12/\n" +
	"\x05input\x18\x01 \x01(\v2\x19.etcdisc.v1.RegisterInputR\x05input\"D\n" +
	"\x10RegisterResponse\x120\n" +
	"\binstance\x18\x01 \x01(\v2\x14.etcdisc.v1.InstanceR\binstance\"D\n" +
	"\x10HeartbeatRequest\x120\n" +
	"\x05input\x18\x01 \x01(\v2\x1a.etcdisc.v1.HeartbeatInputR\x05input\"E\n" +
	"\x11HeartbeatResponse\x120\n" +
	"\binstance\x18\x01 \x01(\v2\x14.etcdisc.v1.InstanceR\binstance\"N\n" +
	"\x15UpdateInstanceRequest\x125\n" +
	"\x05input\x18\x01 \x01(\v2\x1f.etcdisc.v1.UpdateInstanceInputR\x05input\"J\n" +
	"\x16UpdateInstanceResponse\x120\n" +
	"\binstance\x18\x01 \x01(\v2\x14.etcdisc.v1.InstanceR\binstance\"F\n" +
	"\x11DeregisterRequest\x121\n" +
	"\x05input\x18\x01 \x01(\v2\x1b.etcdisc.v1.DeregisterInputR\x05input\",\n" +
	"\x12DeregisterResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\"K\n" +
	"\x0fDiscoverRequest\x128\n" +
	"\x05input\x18\x01 \x01(\v2\".etcdisc.v1.DiscoverySnapshotInputR\x05input\">\n" +
	"\x10DiscoverResponse\x12*\n" +
	"\x05items\x18\x01 \x03(\v2\x14.etcdisc.v1.InstanceR\x05items\"N\n" +
	"\x15WatchInstancesRequest\x125\n" +
	"\x05input\x18\x01 \x01(\v2\x1f.etcdisc.v1.DiscoveryWatchInputR\x05input\"J\n" +
	"\x10ConfigGetRequest\x12\x1c\n" +
	"\tnamespace\x18\x01 \x01(\tR\tnamespace\x12\x18\n" +
	"\aservice\x18\x02 \x01(\tR\aservice\"\xd7\x01\n" +
	"\x11ConfigGetResponse\x12]\n" +
	"\x10effective_config\x18\x01 \x03(\v22.etcdisc.v1.ConfigGetResponse.EffectiveConfigEntryR\x0feffectiveConfig\x1ac\n" +
	"\x14EffectiveConfigEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x125\n" +
	"\x05value\x18\x02 \x01(\v2\x1f.etcdisc.v1.EffectiveConfigItemR\x05value:\x028\x01\"D\n" +
	"\x10ConfigPutRequest\x120\n" +
	"\x05input\x18\x01 \x01(\v2\x1a.etcdisc.v1.ConfigPutInputR\x05input\"?\n" +
	"\x11ConfigPutResponse\x12*\n" +
	"\x04item\x18\x01 \x01(\v2\x16.etcdisc.v1.ConfigItemR\x04item\"J\n" +
	"\x13ConfigDeleteRequest\x123\n" +
	"\x05input\x18\x01 \x01(\v2\x1d.etcdisc.v1.ConfigDeleteInputR\x05input\".\n" +
	"\x14ConfigDeleteResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\"I\n" +
	"\x13WatchConfigsRequest\x122\n" +
	"\x05input\x18\x01 \x01(\v2\x1c.etcdisc.v1.ConfigWatchInputR\x05input\"M\n" +
	"\x16UpsertAgentCardRequest\x123\n" +
	"\x05input\x18\x01 \x01(\v2\x1d.etcdisc.v1.AgentCardPutInputR\x05input\"D\n" +
	"\x17UpsertAgentCardResponse\x12)\n" +
	"\x04card\x18\x01 \x01(\v2\x15.etcdisc.v1.AgentCardR\x04card\"X\n" +
	"\x1bDiscoverCapabilitiesRequest\x129\n" +
	"\x05input\x18\x01 \x01(\v2#.etcdisc.v1.CapabilityDiscoverInputR\x05input\"T\n" +
	"\x1cDiscoverCapabilitiesResponse\x124\n" +
	"\x05items\x18\x01 \x03(\v2\x1e.etcdisc.v1.A2ADiscoveryResultR\x05items2\xc8\x02\n" +
	"\x0fRegistryService\x12E\n" +
	"\bRegister\x12\x1b.etcdisc.v1.RegisterRequest\x1a\x1c.etcdisc.v1.RegisterResponse\x12H\n" +
	"\tHeartbeat\x12\x1c.etcdisc.v1.HeartbeatRequest\x1a\x1d.etcdisc.v1.HeartbeatResponse\x12W\n" +
	"\x0eUpdateInstance\x12!.etcdisc.v1.UpdateInstanceRequest\x1a\".etcdisc.v1.UpdateInstanceResponse\x12K\n" +
	"\n" +
	"Deregister\x12\x1d.etcdisc.v1.DeregisterRequest\x1a\x1e.etcdisc.v1.DeregisterResponse2\xa8\x01\n" +
	"\x10DiscoveryService\x12E\n" +
	"\bDiscover\x12\x1b.etcdisc.v1.DiscoverRequest\x1a\x1c.etcdisc.v1.DiscoverResponse\x12M\n" +
	"\x0eWatchInstances\x12!.etcdisc.v1.WatchInstancesRequest\x1a\x16.etcdisc.v1.WatchEvent0\x012\xca\x02\n" +
	"\rConfigService\x12Q\n" +
	"\x12GetEffectiveConfig\x12\x1c.etcdisc.v1.ConfigGetRequest\x1a\x1d.etcdisc.v1.ConfigGetResponse\x12H\n" +
	"\tPutConfig\x12\x1c.etcdisc.v1.ConfigPutRequest\x1a\x1d.etcdisc.v1.ConfigPutResponse\x12Q\n" +
	"\fDeleteConfig\x12\x1f.etcdisc.v1.ConfigDeleteRequest\x1a .etcdisc.v1.ConfigDeleteResponse\x12I\n" +
	"\fWatchConfigs\x12\x1f.etcdisc.v1.WatchConfigsRequest\x1a\x16.etcdisc.v1.WatchEvent0\x012\xd3\x01\n" +
	"\n" +
	"A2AService\x12Z\n" +
	"\x0fUpsertAgentCard\x12\".etcdisc.v1.UpsertAgentCardRequest\x1a#.etcdisc.v1.UpsertAgentCardResponse\x12i\n" +
	"\x14DiscoverCapabilities\x12'.etcdisc.v1.DiscoverCapabilitiesRequest\x1a(.etcdisc.v1.DiscoverCapabilitiesResponseB(Z&etcdisc/api/proto/etcdisc/v1;etcdiscv1b\x06proto3"

var (
	file_api_proto_etcdisc_v1_etcdisc_proto_rawDescOnce sync.Once
	file_api_proto_etcdisc_v1_etcdisc_proto_rawDescData []byte
)

func file_api_proto_etcdisc_v1_etcdisc_proto_rawDescGZIP() []byte {
	file_api_proto_etcdisc_v1_etcdisc_proto_rawDescOnce.Do(func() {
		file_api_proto_etcdisc_v1_etcdisc_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_etcdisc_v1_etcdisc_proto_rawDesc), len(file_api_proto_etcdisc_v1_etcdisc_proto_rawDesc)))
	})
	return file_api_proto_etcdisc_v1_etcdisc_proto_rawDescData
}

var file_api_proto_etcdisc_v1_etcdisc_proto_msgTypes = make([]protoimpl.MessageInfo, 47)
var file_api_proto_etcdisc_v1_etcdisc_proto_goTypes = []any{
	(*ProbeConfig)(nil),                  // 0: etcdisc.v1.ProbeConfig
	(*Namespace)(nil),                    // 1: etcdisc.v1.Namespace
	(*Instance)(nil),                     // 2: etcdisc.v1.Instance
	(*ConfigItem)(nil),                   // 3: etcdisc.v1.ConfigItem
	(*EffectiveConfigItem)(nil),          // 4: etcdisc.v1.EffectiveConfigItem
	(*AgentCard)(nil),                    // 5: etcdisc.v1.AgentCard
	(*A2ADiscoveryResult)(nil),           // 6: etcdisc.v1.A2ADiscoveryResult
	(*WatchEvent)(nil),                   // 7: etcdisc.v1.WatchEvent
	(*RegisterInput)(nil),                // 8: etcdisc.v1.RegisterInput
	(*HeartbeatInput)(nil),               // 9: etcdisc.v1.HeartbeatInput
	(*UpdateInstanceInput)(nil),          // 10: etcdisc.v1.UpdateInstanceInput
	(*DeregisterInput)(nil),              // 11: etcdisc.v1.DeregisterInput
	(*DiscoverySnapshotInput)(nil),       // 12: etcdisc.v1.DiscoverySnapshotInput
	(*DiscoveryWatchInput)(nil),          // 13: etcdisc.v1.DiscoveryWatchInput
	(*ConfigPutInput)(nil),               // 14: etcdisc.v1.ConfigPutInput
	(*ConfigDeleteInput)(nil),            // 15: etcdisc.v1.ConfigDeleteInput
	(*ConfigWatchInput)(nil),             // 16: etcdisc.v1.ConfigWatchInput
	(*AgentCardPutInput)(nil),            // 17: etcdisc.v1.AgentCardPutInput
	(*CapabilityDiscoverInput)(nil),      // 18: etcdisc.v1.CapabilityDiscoverInput
	(*RegisterRequest)(nil),              // 19: etcdisc.v1.RegisterRequest
	(*RegisterResponse)(nil),             // 20: etcdisc.v1.RegisterResponse
	(*HeartbeatRequest)(nil),             // 21: etcdisc.v1.HeartbeatRequest
	(*HeartbeatResponse)(nil),            // 22: etcdisc.v1.HeartbeatResponse
	(*UpdateInstanceRequest)(nil),        // 23: etcdisc.v1.UpdateInstanceRequest
	(*UpdateInstanceResponse)(nil),       // 24: etcdisc.v1.UpdateInstanceResponse
	(*DeregisterRequest)(nil),            // 25: etcdisc.v1.DeregisterRequest
	(*DeregisterResponse)(nil),           // 26: etcdisc.v1.DeregisterResponse
	(*DiscoverRequest)(nil),              // 27: etcdisc.v1.DiscoverRequest
	(*DiscoverResponse)(nil),             // 28: etcdisc.v1.DiscoverResponse
	(*WatchInstancesRequest)(nil),        // 29: etcdisc.v1.WatchInstancesRequest
	(*ConfigGetRequest)(nil),             // 30: etcdisc.v1.ConfigGetRequest
	(*ConfigGetResponse)(nil),            // 31: etcdisc.v1.ConfigGetResponse
	(*ConfigPutRequest)(nil),             // 32: etcdisc.v1.ConfigPutRequest
	(*ConfigPutResponse)(nil),            // 33: etcdisc.v1.ConfigPutResponse
	(*ConfigDeleteRequest)(nil),          // 34: etcdisc.v1.ConfigDeleteRequest
	(*ConfigDeleteResponse)(nil),         // 35: etcdisc.v1.ConfigDeleteResponse
	(*WatchConfigsRequest)(nil),          // 36: etcdisc.v1.WatchConfigsRequest
	(*UpsertAgentCardRequest)(nil),       // 37: etcdisc.v1.UpsertAgentCardRequest
	(*UpsertAgentCardResponse)(nil),      // 38: etcdisc.v1.UpsertAgentCardResponse
	(*DiscoverCapabilitiesRequest)(nil),  // 39: etcdisc.v1.DiscoverCapabilitiesRequest
	(*DiscoverCapabilitiesResponse)(nil), // 40: etcdisc.v1.DiscoverCapabilitiesResponse
	nil,                                  // 41: etcdisc.v1.Instance.MetadataEntry
	nil,                                  // 42: etcdisc.v1.AgentCard.MetadataEntry
	nil,                                  // 43: etcdisc.v1.A2ADiscoveryResult.MetadataEntry
	nil,                                  // 44: etcdisc.v1.UpdateInstanceInput.MetadataEntry
	nil,                                  // 45: etcdisc.v1.DiscoverySnapshotInput.MetadataEntry
	nil,                                  // 46: etcdisc.v1.ConfigGetResponse.EffectiveConfigEntry
	(*timestamppb.Timestamp)(nil),        // 47: google.protobuf.Timestamp
	(*wrapperspb.Int32Value)(nil),        // 48: google.protobuf.Int32Value
	(*wrapperspb.StringValue)(nil),       // 49: google.protobuf.StringValue
	(*wrapperspb.BoolValue)(nil),         // 50: google.protobuf.BoolValue
}
var file_api_proto_etcdisc_v1_etcdisc_proto_depIdxs = []int32{
	47, // 0: etcdisc.v1.Namespace.created_at:type_name -> google.protobuf.Timestamp
	47, // 1: etcdisc.v1.Namespace.updated_at:type_name -> google.protobuf.Timestamp
	41, // 2: etcdisc.v1.Instance.metadata:type_name -> etcdisc.v1.Instance.MetadataEntry
	0,  // 3: etcdisc.v1.Instance.probe_config:type_name -> etcdisc.v1.ProbeConfig
	47, // 4: etcdisc.v1.Instance.last_heartbeat_at:type_name -> google.protobuf.Timestamp
	47, // 5: etcdisc.v1.Instance.last_probe_at:type_name -> google.protobuf.Timestamp
	47, // 6: etcdisc.v1.Instance.created_at:type_name -> google.protobuf.Timestamp
	47, // 7: etcdisc.v1.Instance.updated_at:type_name -> google.protobuf.Timestamp
	47, // 8: etcdisc.v1.Instance.status_updated_at:type_name -> google.protobuf.Timestamp
	47, // 9: etcdisc.v1.ConfigItem.created_at:type_name -> google.protobuf.Timestamp
	47, // 10: etcdisc.v1.ConfigItem.updated_at:type_name -> google.protobuf.Timestamp
	42, // 11: etcdisc.v1.AgentCard.metadata:type_name -> etcdisc.v1.AgentCard.MetadataEntry
	47, // 12: etcdisc.v1.AgentCard.created_at:type_name -> google.protobuf.Timestamp
	47, // 13: etcdisc.v1.AgentCard.updated_at:type_name -> google.protobuf.Timestamp
	43, // 14: etcdisc.v1.A2ADiscoveryResult.metadata:type_name -> etcdisc.v1.A2ADiscoveryResult.MetadataEntry
	2,  // 15: etcdisc.v1.RegisterInput.instance:type_name -> etcdisc.v1.Instance
	48, // 16: etcdisc.v1.UpdateInstanceInput.weight:type_name -> google.protobuf.Int32Value
	44, // 17: etcdisc.v1.UpdateInstanceInput.metadata:type_name -> etcdisc.v1.UpdateInstanceInput.MetadataEntry
	49, // 18: etcdisc.v1.UpdateInstanceInput.version:type_name -> google.protobuf.StringValue
	45, // 19: etcdisc.v1.DiscoverySnapshotInput.metadata:type_name -> etcdisc.v1.DiscoverySnapshotInput.MetadataEntry
	50, // 20: etcdisc.v1.DiscoverySnapshotInput.healthy_only:type_name -> google.protobuf.BoolValue
	50, // 21: etcdisc.v1.DiscoveryWatchInput.healthy_only:type_name -> google.protobuf.BoolValue
	3,  // 22: etcdisc.v1.ConfigPutInput.item:type_name -> etcdisc.v1.ConfigItem
	5,  // 23: etcdisc.v1.AgentCardPutInput.card:type_name -> etcdisc.v1.AgentCard
	50, // 24: etcdisc.v1.CapabilityDiscoverInput.include_unhealthy:type_name -> google.protobuf.BoolValue
	8,  // 25: etcdisc.v1.RegisterRequest.input:type_name -> etcdisc.v1.RegisterInput
	2,  // 26: etcdisc.v1.RegisterResponse.instance:type_name -> etcdisc.v1.Instance
	9,  // 27: etcdisc.v1.HeartbeatRequest.input:type_name -> etcdisc.v1.HeartbeatInput
	2,  // 28: etcdisc.v1.HeartbeatResponse.instance:type_name -> etcdisc.v1.Instance
	10, // 29: etcdisc.v1.UpdateInstanceRequest.input:type_name -> etcdisc.v1.UpdateInstanceInput
	2,  // 30: etcdisc.v1.UpdateInstanceResponse.instance:type_name -> etcdisc.v1.Instance
	11, // 31: etcdisc.v1.DeregisterRequest.input:type_name -> etcdisc.v1.DeregisterInput
	12, // 32: etcdisc.v1.DiscoverRequest.input:type_name -> etcdisc.v1.DiscoverySnapshotInput
	2,  // 33: etcdisc.v1.DiscoverResponse.items:type_name -> etcdisc.v1.Instance
	13, // 34: etcdisc.v1.WatchInstancesRequest.input:type_name -> etcdisc.v1.DiscoveryWatchInput
	46, // 35: etcdisc.v1.ConfigGetResponse.effective_config:type_name -> etcdisc.v1.ConfigGetResponse.EffectiveConfigEntry
	14, // 36: etcdisc.v1.ConfigPutRequest.input:type_name -> etcdisc.v1.ConfigPutInput
	3,  // 37: etcdisc.v1.ConfigPutResponse.item:type_name -> etcdisc.v1.ConfigItem
	15, // 38: etcdisc.v1.ConfigDeleteRequest.input:type_name -> etcdisc.v1.ConfigDeleteInput
	16, // 39: etcdisc.v1.WatchConfigsRequest.input:type_name -> etcdisc.v1.ConfigWatchInput
	17, // 40: etcdisc.v1.UpsertAgentCardRequest.input:type_name -> etcdisc.v1.AgentCardPutInput
	5,  // 41: etcdisc.v1.UpsertAgentCardResponse.card:type_name -> etcdisc.v1.AgentCard
	18, // 42: etcdisc.v1.DiscoverCapabilitiesRequest.input:type_name -> etcdisc.v1.CapabilityDiscoverInput
	6,  // 43: etcdisc.v1.DiscoverCapabilitiesResponse.items:type_name -> etcdisc.v1.A2ADiscoveryResult
	4,  // 44: etcdisc.v1.ConfigGetResponse.EffectiveConfigEntry.value:type_name -> etcdisc.v1.EffectiveConfigItem
	19, // 45: etcdisc.v1.RegistryService.Register:input_type -> etcdisc.v1.RegisterRequest
	21, // 46: etcdisc.v1.RegistryService.Heartbeat:input_type -> etcdisc.v1.HeartbeatRequest
	23, // 47: etcdisc.v1.RegistryService.UpdateInstance:input_type -> etcdisc.v1.UpdateInstanceRequest
	25, // 48: etcdisc.v1.RegistryService.Deregister:input_type -> etcdisc.v1.DeregisterRequest
	27, // 49: etcdisc.v1.DiscoveryService.Discover:input_type -> etcdisc.v1.DiscoverRequest
	29, // 50: etcdisc.v1.DiscoveryService.WatchInstances:input_type -> etcdisc.v1.WatchInstancesRequest
	30, // 51: etcdisc.v1.ConfigService.GetEffectiveConfig:input_type -> etcdisc.v1.ConfigGetRequest
	32, // 52: etcdisc.v1.ConfigService.PutConfig:input_type -> etcdisc.v1.ConfigPutRequest
	34, // 53: etcdisc.v1.ConfigService.DeleteConfig:input_type -> etcdisc.v1.ConfigDeleteRequest
	36, // 54: etcdisc.v1.ConfigService.WatchConfigs:input_type -> etcdisc.v1.WatchConfigsRequest
	37, // 55: etcdisc.v1.A2AService.UpsertAgentCard:input_type -> etcdisc.v1.UpsertAgentCardRequest
	39, // 56: etcdisc.v1.A2AService.DiscoverCapabilities:input_type -> etcdisc.v1.DiscoverCapabilitiesRequest
	20, // 57: etcdisc.v1.RegistryService.Register:output_type -> etcdisc.v1.RegisterResponse
	22, // 58: etcdisc.v1.RegistryService.Heartbeat:output_type -> etcdisc.v1.HeartbeatResponse
	24, // 59: etcdisc.v1.RegistryService.UpdateInstance:output_type -> etcdisc.v1.UpdateInstanceResponse
	26, // 60: etcdisc.v1.RegistryService.Deregister:output_type -> etcdisc.v1.DeregisterResponse
	28, // 61: etcdisc.v1.DiscoveryService.Discover:output_type -> etcdisc.v1.DiscoverResponse
	7,  // 62: etcdisc.v1.DiscoveryService.WatchInstances:output_type -> etcdisc.v1.WatchEvent
	31, // 63: etcdisc.v1.ConfigService.GetEffectiveConfig:output_type -> etcdisc.v1.ConfigGetResponse
	33, // 64: etcdisc.v1.ConfigService.PutConfig:output_type -> etcdisc.v1.ConfigPutResponse
	35, // 65: etcdisc.v1.ConfigService.DeleteConfig:output_type -> etcdisc.v1.ConfigDeleteResponse
	7,  // 66: etcdisc.v1.ConfigService.WatchConfigs:output_type -> etcdisc.v1.WatchEvent
	38, // 67: etcdisc.v1.A2AService.UpsertAgentCard:output_type -> etcdisc.v1.UpsertAgentCardResponse
	40, // 68: etcdisc.v1.A2AService.DiscoverCapabilities:output_type -> etcdisc.v1.DiscoverCapabilitiesResponse
	57, // [57:69] is the sub-list for method output_type
	45, // [45:57] is the sub-list for method input_type
	45, // [45:45] is the sub-list for extension type_name
	45, // [45:45] is the sub-list for extension extendee
	0,  // [0:45] is the sub-list for field type_name
}

func init() { file_api_proto_etcdisc_v1_etcdisc_proto_init() }
func file_api_proto_etcdisc_v1_etcdisc_proto_init() {
	if File_api_proto_etcdisc_v1_etcdisc_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_etcdisc_v1_etcdisc_proto_rawDesc), len(file_api_proto_etcdisc_v1_etcdisc_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   47,
			NumExtensions: 0,
			NumServices:   4,
		},
		GoTypes:           file_api_proto_etcdisc_v1_etcdisc_proto_goTypes,
		DependencyIndexes: file_api_proto_etcdisc_v1_etcdisc_proto_depIdxs,
		MessageInfos:      file_api_proto_etcdisc_v1_etcdisc_proto_msgTypes,
	}.Build()
	File_api_proto_etcdisc_v1_etcdisc_proto = out.File
	file_api_proto_etcdisc_v1_etcdisc_proto_goTypes = nil
	file_api_proto_etcdisc_v1_etcdisc_proto_depIdxs = nil
}
